export const GLOSSARY = {
  "#": "Pitches of this type thrown.",
  ABS: "Automated Ball-Strike system: a challenged call is reviewed by pitch tracking.",
  AVG: "Batting average: hits per at-bat.",
  "BB%": "Walk rate: walks per plate appearance.",
  BF: "Batters faced.",
  "Chase%": "Share of pitches outside the strike zone that the batter swung at.",
  "CSW%": "Called strikes plus whiffs, as a share of all pitches.",
  E: "Errors.",
  "Exit velo": "Average speed of the ball off the bat, in mph.",
  "FB velo": "Average speed of four-seam fastballs and sinkers, in mph.",
  GB: "Games back: how far a team trails the division leader.",
  GS: "Games started.",
  H: "Hits.",
  "Hard-hit%": "Share of batted balls hit 95 mph or harder.",
  HR: "Home runs.",
  IP: "Innings pitched; .1 and .2 mean one and two outs.",
  ISO: "Isolated power: slugging minus average, measuring extra-base power.",
  K: "Strikeouts.",
  "K%": "Strikeout rate: strikeouts per plate appearance.",
  L: "Losses; for a pitcher, charged with the team's loss.",
  LHP: "Left-handed pitcher.",
  Lg: "League average.",
  OBP: "On-base percentage: how often a batter reaches base by hit, walk or hit-by-pitch.",
  OPS: "On-base plus slugging: OBP and SLG added together.",
  PA: "Plate appearances.",
  Pct: "Winning percentage: wins divided by games played.",
  Pythag: "Expected record from runs scored and allowed (Pythagorean formula, exponent 1.83).",
  R: "Runs.",
  RA9: "Runs allowed per nine innings, earned or not.",
  RHP: "Right-handed pitcher.",
  RISP: "Runners in scoring position: a runner on second or third.",
  S: "Save: the reliever who finished a close win.",
  SLG: "Slugging percentage: total bases per at-bat.",
  Usage: "Share of all pitches that were this type.",
  Velo: "Average speed of this pitch, in mph.",
  W: "Wins; for a pitcher, credited with the team's win.",
  WHIP: "Walks plus hits per inning pitched.",
  "Whiff%": "Swings and misses per swing.",
  X: "Extra innings.",
  "Z-contact%": "Share of swings at strike-zone pitches that made contact.",
} as const;

export type GlossaryTerm = keyof typeof GLOSSARY;
