export const GLOSSARY = {
  "#": "Pitches of this type thrown.",
  "2B": "Doubles.",
  "3B": "Triples.",
  ABS: "Automated Ball-Strike system: a challenged call is reviewed by pitch tracking.",
  AB: "At-bats: plate appearances minus walks, hit-by-pitches, sacrifices and interference.",
  AVG: "Batting average: hits per at-bat.",
  "Batted balls": "Balls in play with a tracked exit velocity.",
  Batter: "The batter on the play.",
  BB: "Walks.",
  "BB%": "Walk rate: walks per plate appearance.",
  "Barrel%": "Share of batted balls that were barrels: 98+ mph in a launch-angle band that starts at 26–30° and widens with speed (approximates Statcast's definition).",
  BF: "Batters faced.",
  "Chase%": "Share of pitches outside the strike zone that the batter swung at.",
  Count: "Balls and strikes before the pitch.",
  "CSW%": "Called strikes plus whiffs, as a share of all pitches.",
  Diff: "Run differential: runs scored minus runs allowed.",
  Dec: "Decision: W (win), L (loss), S (save), H (hold) or BS (blown save).",
  Distance: "Projected distance of the batted ball, in feet.",
  E: "Errors.",
  ER: "Earned runs: runs that scored without the help of an error or passed ball.",
  ERA: "Earned run average: earned runs allowed per nine innings.",
  "Exit velo": "Average speed of the ball off the bat, in mph.",
  "FB velo": "Average speed of four-seam fastballs and sinkers, in mph.",
  Game: "The game it happened in.",
  GB: "Games back: how far a team trails the division leader.",
  GS: "Games started.",
  H: "Hits.",
  HB: "Horizontal break: sideways movement of the pitch compared with a spinless pitch, in inches.",
  "Hard-hit%": "Share of batted balls hit 95 mph or harder.",
  HR: "Home runs.",
  IP: "Innings pitched; .1 and .2 mean one and two outs.",
  ISO: "Isolated power: slugging minus average, measuring extra-base power.",
  IVB: "Induced vertical break: how much the pitch rises or drops compared with a spinless pitch (gravity removed), in inches.",
  K: "Strikeouts.",
  "K%": "Strikeout rate: strikeouts per plate appearance.",
  L: "Losses; for a pitcher, charged with the team's loss.",
  L10: "Record over the last 10 games.",
  LHB: "Left-handed batter.",
  LHP: "Left-handed pitcher.",
  MPH: "Speed in miles per hour.",
  NP: "Number of pitches thrown.",
  Lg: "League average.",
  OBP: "On-base percentage: how often a batter reaches base by hit, walk or hit-by-pitch.",
  OPS: "On-base plus slugging: OBP and SLG added together.",
  PA: "Plate appearances.",
  Pct: "Winning percentage: wins divided by games played.",
  Percentile: "Rank among qualified players this season, from 0 to 100; higher is always better.",
  Pitch: "Pitch type.",
  Pitcher: "The pitcher on the play.",
  Pos: "Position played.",
  Pythag: "Expected record from runs scored and allowed (Pythagorean formula, exponent 1.83).",
  R: "Runs.",
  RA9: "Runs allowed per nine innings, earned or not.",
  RBI: "Runs batted in.",
  Result: "How the pitch or play ended.",
  RHB: "Right-handed batter.",
  RHP: "Right-handed pitcher.",
  RISP: "Runners in scoring position: a runner on second or third.",
  S: "Save: the reliever who finished a close win.",
  SB: "Stolen bases.",
  SLG: "Slugging percentage: total bases per at-bat.",
  Spin: "Average spin rate of this pitch, in revolutions per minute.",
  Strk: "Current streak: consecutive wins (W) or losses (L).",
  Usage: "Share of all pitches that were this type.",
  Velo: "Average speed of this pitch, in mph.",
  W: "Wins; for a pitcher, credited with the team's win.",
  WCGB: "Wild card games back: how far a team trails the last wild card spot; + means it holds a spot by that many games.",
  WHIP: "Walks plus hits per inning pitched.",
  "Whiff%": "Swings and misses per swing.",
  X: "Extra innings.",
  "Z-contact%": "Share of swings at strike-zone pitches that made contact.",
} as const;

export type GlossaryTerm = keyof typeof GLOSSARY;
