CREATE TYPE IF NOT EXISTS inning_half AS ENUM ('top', 'bottom');
CREATE TYPE IF NOT EXISTS handedness AS ENUM ('L', 'R', 'S');

CREATE TABLE IF NOT EXISTS plays (
  game_pk                  INTEGER NOT NULL,
  season                   INTEGER NOT NULL,
  at_bat_index             INTEGER NOT NULL,
  inning                   INTEGER NOT NULL,
  half                     inning_half NOT NULL,
  batter_id                INTEGER NOT NULL,
  pitcher_id               INTEGER NOT NULL,
  bat_side                 handedness,
  pitch_hand               handedness,
  men_on_base              VARCHAR,
  event                    VARCHAR,
  event_type               VARCHAR,
  description              VARCHAR,
  rbi                      INTEGER,
  is_out                   BOOLEAN,
  is_scoring_play          BOOLEAN,
  final_balls              INTEGER,
  final_strikes            INTEGER,
  outs_after               INTEGER,
  home_score_after         INTEGER,
  away_score_after         INTEGER,
  pitch_count              INTEGER NOT NULL,
  launch_speed             DOUBLE,
  launch_angle             DOUBLE,
  total_distance           DOUBLE,
  trajectory               VARCHAR,
  hardness                 VARCHAR,
  hit_location             VARCHAR,
  hit_coord_x              DOUBLE,
  hit_coord_y              DOUBLE,
  has_review               BOOLEAN,
  review_type              VARCHAR,
  review_overturned        BOOLEAN,
  review_challenge_team_id INTEGER,
  review_player_id         INTEGER,
  start_time               TIMESTAMPTZ,
  end_time                 TIMESTAMPTZ,
  PRIMARY KEY (game_pk, at_bat_index)
);

CREATE TABLE IF NOT EXISTS pitches (
  game_pk                INTEGER NOT NULL,
  season                 INTEGER NOT NULL,
  at_bat_index           INTEGER NOT NULL,
  pitch_index            INTEGER NOT NULL,
  play_id                VARCHAR,
  pitch_number           INTEGER,
  inning                 INTEGER NOT NULL,
  half                   inning_half NOT NULL,
  batter_id              INTEGER NOT NULL,
  pitcher_id             INTEGER NOT NULL,
  bat_side               handedness,
  pitch_hand             handedness,
  balls_before           INTEGER NOT NULL,
  strikes_before         INTEGER NOT NULL,
  outs_before            INTEGER NOT NULL,
  pitch_type             VARCHAR,
  pitch_type_desc        VARCHAR,
  type_confidence        DOUBLE,
  call_code              VARCHAR,
  call_desc              VARCHAR,
  description            VARCHAR,
  is_in_play             BOOLEAN,
  is_strike              BOOLEAN,
  is_ball                BOOLEAN,
  is_out                 BOOLEAN,
  start_speed            DOUBLE,
  end_speed              DOUBLE,
  spin_rate              DOUBLE,
  spin_direction         DOUBLE,
  extension              DOUBLE,
  plate_time             DOUBLE,
  plate_x                DOUBLE,
  plate_z                DOUBLE,
  pfx_x                  DOUBLE,
  pfx_z                  DOUBLE,
  x0                     DOUBLE,
  y0                     DOUBLE,
  z0                     DOUBLE,
  vx0                    DOUBLE,
  vy0                    DOUBLE,
  vz0                    DOUBLE,
  ax                     DOUBLE,
  ay                     DOUBLE,
  az                     DOUBLE,
  break_angle            DOUBLE,
  break_length           DOUBLE,
  break_y                DOUBLE,
  break_vertical         DOUBLE,
  induced_vertical_break DOUBLE,
  horizontal_break       DOUBLE,
  zone                   INTEGER,
  sz_top                 DOUBLE,
  sz_bottom              DOUBLE,
  launch_speed           DOUBLE,
  launch_angle           DOUBLE,
  total_distance         DOUBLE,
  trajectory             VARCHAR,
  hardness               VARCHAR,
  hit_location           VARCHAR,
  abs_challenged         BOOLEAN NOT NULL,
  abs_overturned         BOOLEAN,
  abs_challenge_team_id  INTEGER,
  abs_challenger_id      INTEGER,
  start_time             TIMESTAMPTZ,
  end_time               TIMESTAMPTZ,
  PRIMARY KEY (game_pk, at_bat_index, pitch_index)
);

CREATE TABLE IF NOT EXISTS players (
  player_id          INTEGER PRIMARY KEY,
  season             INTEGER NOT NULL,
  full_name          VARCHAR NOT NULL,
  first_name         VARCHAR,
  last_name          VARCHAR,
  boxscore_name      VARCHAR,
  primary_number     VARCHAR,
  primary_position   VARCHAR,
  bat_side           handedness,
  pitch_hand         handedness,
  birth_date         DATE,
  height             VARCHAR,
  weight             INTEGER,
  mlb_debut_date     DATE,
  active             BOOLEAN,
  sz_top             DOUBLE,
  sz_bottom          DOUBLE,
  source_game_pk     INTEGER NOT NULL,
  source_date        DATE NOT NULL,
  source_game_number INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS teams (
  team_id            INTEGER PRIMARY KEY,
  season             INTEGER NOT NULL,
  name               VARCHAR NOT NULL,
  team_name          VARCHAR,
  abbreviation       VARCHAR,
  location_name      VARCHAR,
  short_name         VARCHAR,
  team_code          VARCHAR,
  league_id          INTEGER,
  league_name        VARCHAR,
  division_id        INTEGER,
  division_name      VARCHAR,
  venue_id           INTEGER,
  venue_name         VARCHAR,
  source_game_pk     INTEGER NOT NULL,
  source_date        DATE NOT NULL,
  source_game_number INTEGER NOT NULL
);
