ALTER TABLE games ADD COLUMN IF NOT EXISTS outs INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS on_first BOOLEAN DEFAULT false;
ALTER TABLE games ADD COLUMN IF NOT EXISTS on_second BOOLEAN DEFAULT false;
ALTER TABLE games ADD COLUMN IF NOT EXISTS on_third BOOLEAN DEFAULT false;
ALTER TABLE games ALTER COLUMN on_first SET NOT NULL;
ALTER TABLE games ALTER COLUMN on_second SET NOT NULL;
ALTER TABLE games ALTER COLUMN on_third SET NOT NULL;
