ALTER TABLE games ADD COLUMN IF NOT EXISTS series_game_number INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS games_in_series INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS series_result VARCHAR;
