CREATE TYPE handedness AS ENUM ('L', 'R', 'S');

CREATE TYPE inning_half AS ENUM ('top', 'bottom');

CREATE TYPE team_side AS ENUM ('home', 'away');

CREATE MACRO is_barrel(launch_speed, launch_angle) AS ((launch_speed >= 98) AND (launch_angle BETWEEN greatest(8, (26 - (launch_speed - 98))) AND least(50, (30 + (1.5 * (launch_speed - 98))))));

CREATE TABLE batted_ball_days (
  season INTEGER NOT NULL,
  official_date DATE NOT NULL,
  player_id INTEGER,
  batted_balls BIGINT NOT NULL,
  hard_hits BIGINT NOT NULL,
  barrels BIGINT NOT NULL,
  launch_speed_sum DOUBLE
);

CREATE TABLE event_leaders (
  season INTEGER NOT NULL,
  official_date DATE NOT NULL,
  board VARCHAR NOT NULL,
  player_id INTEGER,
  opponent_id INTEGER,
  value DOUBLE NOT NULL,
  pitch_type VARCHAR,
  count VARCHAR,
  result VARCHAR,
  game_pk INTEGER NOT NULL,
  at_bat_index INTEGER NOT NULL,
  pitch_index INTEGER NOT NULL
);

CREATE TABLE event_types (
  event_type VARCHAR NOT NULL,
  is_plate_appearance BOOLEAN NOT NULL,
  is_at_bat BOOLEAN NOT NULL,
  is_ball_in_play BOOLEAN NOT NULL,
  is_walk BOOLEAN NOT NULL,
  is_strikeout BOOLEAN NOT NULL,
  bases INTEGER NOT NULL,
  PRIMARY KEY(event_type)
);

CREATE TABLE game_decisions (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  winner_id INTEGER NOT NULL,
  loser_id INTEGER,
  save_id INTEGER,
  PRIMARY KEY(game_pk)
);

CREATE TABLE game_player_bios (
  game_pk INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  full_name VARCHAR NOT NULL,
  first_name VARCHAR,
  last_name VARCHAR,
  boxscore_name VARCHAR,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  birth_date DATE,
  height VARCHAR,
  weight INTEGER,
  mlb_debut_date DATE,
  active BOOLEAN,
  sz_top DOUBLE,
  sz_bottom DOUBLE,
  source_date DATE NOT NULL,
  source_game_number INTEGER NOT NULL,
  PRIMARY KEY(game_pk, player_id)
);

CREATE TABLE game_players (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side ENUM('home', 'away') NOT NULL,
  jersey_number VARCHAR,
  position VARCHAR,
  all_positions VARCHAR[],
  batting_order INTEGER,
  is_substitute BOOLEAN,
  played BOOLEAN NOT NULL,
  PRIMARY KEY(game_pk, player_id, side)
);

CREATE TABLE game_starters (
  game_pk INTEGER NOT NULL,
  side ENUM('home', 'away') NOT NULL,
  pitcher_id INTEGER,
  PRIMARY KEY(game_pk, side)
);

CREATE TABLE game_teams (
  game_pk INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  season INTEGER NOT NULL,
  name VARCHAR NOT NULL,
  team_name VARCHAR,
  abbreviation VARCHAR,
  location_name VARCHAR,
  short_name VARCHAR,
  team_code VARCHAR,
  league_id INTEGER,
  league_name VARCHAR,
  division_id INTEGER,
  division_name VARCHAR,
  venue_id INTEGER,
  venue_name VARCHAR,
  source_date DATE NOT NULL,
  source_game_number INTEGER NOT NULL,
  PRIMARY KEY(game_pk, team_id)
);

CREATE TABLE games (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  official_date DATE NOT NULL,
  game_type VARCHAR NOT NULL,
  game_number INTEGER NOT NULL,
  abstract_state VARCHAR NOT NULL,
  coded_state VARCHAR NOT NULL,
  detailed_state VARCHAR NOT NULL,
  home_team_id INTEGER NOT NULL,
  away_team_id INTEGER NOT NULL,
  home_score INTEGER,
  away_score INTEGER,
  inning INTEGER,
  inning_half VARCHAR,
  start_utc TIMESTAMP WITH TIME ZONE NOT NULL,
  venue_name VARCHAR,
  home_record VARCHAR,
  away_record VARCHAR,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  double_header VARCHAR,
  rescheduled_from DATE,
  outs INTEGER,
  on_first BOOLEAN NOT NULL DEFAULT CAST('f' AS BOOLEAN),
  on_second BOOLEAN NOT NULL DEFAULT CAST('f' AS BOOLEAN),
  on_third BOOLEAN NOT NULL DEFAULT CAST('f' AS BOOLEAN),
  home_probable_id INTEGER,
  home_probable_name VARCHAR,
  away_probable_id INTEGER,
  away_probable_name VARCHAR,
  series_game_number INTEGER,
  games_in_series INTEGER,
  series_result VARCHAR,
  PRIMARY KEY(game_pk)
);

CREATE TABLE linescores (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  inning INTEGER NOT NULL,
  half ENUM('top', 'bottom') NOT NULL,
  runs INTEGER,
  hits INTEGER,
  errors INTEGER,
  left_on_base INTEGER,
  PRIMARY KEY(game_pk, inning, half)
);

CREATE TABLE pitch_outcome_days (
  season INTEGER NOT NULL,
  official_date DATE NOT NULL,
  player_id INTEGER,
  pitches BIGINT NOT NULL,
  swings BIGINT NOT NULL,
  whiffs BIGINT NOT NULL,
  called_strikes BIGINT NOT NULL,
  out_of_zone_pitches BIGINT NOT NULL,
  chases BIGINT NOT NULL,
  zone_swings BIGINT NOT NULL,
  zone_contacts BIGINT NOT NULL
);

CREATE TABLE pitch_outcomes (
  game_pk INTEGER,
  season INTEGER,
  at_bat_index INTEGER,
  pitch_index INTEGER,
  play_id VARCHAR,
  pitch_number INTEGER,
  inning INTEGER,
  half ENUM('top', 'bottom'),
  batter_id INTEGER,
  pitcher_id INTEGER,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  balls_before INTEGER,
  strikes_before INTEGER,
  outs_before INTEGER,
  pitch_type VARCHAR,
  pitch_type_desc VARCHAR,
  type_confidence DOUBLE,
  call_code VARCHAR,
  call_desc VARCHAR,
  description VARCHAR,
  is_in_play BOOLEAN,
  is_strike BOOLEAN,
  is_ball BOOLEAN,
  is_out BOOLEAN,
  start_speed DOUBLE,
  end_speed DOUBLE,
  spin_rate DOUBLE,
  spin_direction DOUBLE,
  extension DOUBLE,
  plate_time DOUBLE,
  plate_x DOUBLE,
  plate_z DOUBLE,
  pfx_x DOUBLE,
  pfx_z DOUBLE,
  x0 DOUBLE,
  y0 DOUBLE,
  z0 DOUBLE,
  vx0 DOUBLE,
  vy0 DOUBLE,
  vz0 DOUBLE,
  ax DOUBLE,
  ay DOUBLE,
  az DOUBLE,
  break_angle DOUBLE,
  break_length DOUBLE,
  break_y DOUBLE,
  break_vertical DOUBLE,
  induced_vertical_break DOUBLE,
  horizontal_break DOUBLE,
  zone INTEGER,
  sz_top DOUBLE,
  sz_bottom DOUBLE,
  launch_speed DOUBLE,
  launch_angle DOUBLE,
  total_distance DOUBLE,
  trajectory VARCHAR,
  hardness VARCHAR,
  hit_location VARCHAR,
  abs_challenged BOOLEAN,
  abs_overturned BOOLEAN,
  abs_challenge_team_id INTEGER,
  abs_challenger_id INTEGER,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  batting_team_id INTEGER,
  fielding_team_id INTEGER,
  official_date DATE,
  game_type VARCHAR,
  coded_state VARCHAR,
  is_swing BOOLEAN,
  is_whiff BOOLEAN,
  is_called_strike BOOLEAN,
  is_in_zone BOOLEAN,
  is_fastball BOOLEAN
);

CREATE TABLE pitches (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  at_bat_index INTEGER NOT NULL,
  pitch_index INTEGER NOT NULL,
  play_id VARCHAR,
  pitch_number INTEGER,
  inning INTEGER NOT NULL,
  half ENUM('top', 'bottom') NOT NULL,
  batter_id INTEGER NOT NULL,
  pitcher_id INTEGER NOT NULL,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  balls_before INTEGER NOT NULL,
  strikes_before INTEGER NOT NULL,
  outs_before INTEGER NOT NULL,
  pitch_type VARCHAR,
  pitch_type_desc VARCHAR,
  type_confidence DOUBLE,
  call_code VARCHAR,
  call_desc VARCHAR,
  description VARCHAR,
  is_in_play BOOLEAN,
  is_strike BOOLEAN,
  is_ball BOOLEAN,
  is_out BOOLEAN,
  start_speed DOUBLE,
  end_speed DOUBLE,
  spin_rate DOUBLE,
  spin_direction DOUBLE,
  extension DOUBLE,
  plate_time DOUBLE,
  plate_x DOUBLE,
  plate_z DOUBLE,
  pfx_x DOUBLE,
  pfx_z DOUBLE,
  x0 DOUBLE,
  y0 DOUBLE,
  z0 DOUBLE,
  vx0 DOUBLE,
  vy0 DOUBLE,
  vz0 DOUBLE,
  ax DOUBLE,
  ay DOUBLE,
  az DOUBLE,
  break_angle DOUBLE,
  break_length DOUBLE,
  break_y DOUBLE,
  break_vertical DOUBLE,
  induced_vertical_break DOUBLE,
  horizontal_break DOUBLE,
  zone INTEGER,
  sz_top DOUBLE,
  sz_bottom DOUBLE,
  launch_speed DOUBLE,
  launch_angle DOUBLE,
  total_distance DOUBLE,
  trajectory VARCHAR,
  hardness VARCHAR,
  hit_location VARCHAR,
  abs_challenged BOOLEAN NOT NULL,
  abs_overturned BOOLEAN,
  abs_challenge_team_id INTEGER,
  abs_challenger_id INTEGER,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(game_pk, at_bat_index, pitch_index)
);

CREATE TABLE plate_appearances (
  game_pk INTEGER,
  season INTEGER,
  at_bat_index INTEGER,
  inning INTEGER,
  half ENUM('top', 'bottom'),
  batter_id INTEGER,
  pitcher_id INTEGER,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  men_on_base VARCHAR,
  event VARCHAR,
  event_type VARCHAR,
  description VARCHAR,
  rbi INTEGER,
  is_out BOOLEAN,
  is_scoring_play BOOLEAN,
  final_balls INTEGER,
  final_strikes INTEGER,
  outs_after INTEGER,
  home_score_after INTEGER,
  away_score_after INTEGER,
  pitch_count INTEGER,
  launch_speed DOUBLE,
  launch_angle DOUBLE,
  total_distance DOUBLE,
  trajectory VARCHAR,
  hardness VARCHAR,
  hit_location VARCHAR,
  hit_coord_x DOUBLE,
  hit_coord_y DOUBLE,
  has_review BOOLEAN,
  review_type VARCHAR,
  review_overturned BOOLEAN,
  review_challenge_team_id INTEGER,
  review_player_id INTEGER,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  batting_team_id INTEGER,
  fielding_team_id INTEGER,
  official_date DATE,
  game_type VARCHAR,
  coded_state VARCHAR,
  is_at_bat BOOLEAN,
  is_ball_in_play BOOLEAN,
  is_walk BOOLEAN,
  is_strikeout BOOLEAN,
  bases INTEGER
);

CREATE TABLE play_events (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  at_bat_index INTEGER NOT NULL,
  event_index INTEGER NOT NULL,
  kind VARCHAR,
  event_type VARCHAR,
  call_code VARCHAR,
  description VARCHAR,
  is_scoring_play BOOLEAN,
  player_id INTEGER,
  start_time TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(game_pk, at_bat_index, event_index)
);

CREATE TABLE player_game_batting (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  plate_appearances INTEGER NOT NULL,
  at_bats INTEGER NOT NULL,
  runs INTEGER NOT NULL,
  hits INTEGER NOT NULL,
  doubles INTEGER NOT NULL,
  triples INTEGER NOT NULL,
  home_runs INTEGER NOT NULL,
  total_bases INTEGER NOT NULL,
  rbi INTEGER NOT NULL,
  walks INTEGER NOT NULL,
  intentional_walks INTEGER NOT NULL,
  strikeouts INTEGER NOT NULL,
  hit_by_pitch INTEGER NOT NULL,
  sac_flies INTEGER NOT NULL,
  sac_bunts INTEGER NOT NULL,
  stolen_bases INTEGER NOT NULL,
  caught_stealing INTEGER NOT NULL,
  grounded_into_double_play INTEGER NOT NULL,
  left_on_base INTEGER NOT NULL,
  PRIMARY KEY(game_pk, player_id, team_id)
);

CREATE TABLE player_game_pitching (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  is_starter BOOLEAN NOT NULL,
  outs INTEGER NOT NULL,
  batters_faced INTEGER NOT NULL,
  pitches INTEGER NOT NULL,
  strikes INTEGER NOT NULL,
  hits INTEGER NOT NULL,
  runs INTEGER NOT NULL,
  earned_runs INTEGER NOT NULL,
  home_runs INTEGER NOT NULL,
  walks INTEGER NOT NULL,
  intentional_walks INTEGER NOT NULL,
  strikeouts INTEGER NOT NULL,
  hit_batsmen INTEGER NOT NULL,
  wild_pitches INTEGER NOT NULL,
  balks INTEGER NOT NULL,
  inherited_runners INTEGER NOT NULL,
  inherited_runners_scored INTEGER NOT NULL,
  is_win BOOLEAN NOT NULL,
  is_loss BOOLEAN NOT NULL,
  is_save BOOLEAN NOT NULL,
  is_hold BOOLEAN NOT NULL,
  is_blown_save BOOLEAN NOT NULL,
  PRIMARY KEY(game_pk, player_id, team_id)
);

CREATE TABLE player_season_counts (
  season INTEGER NOT NULL,
  role VARCHAR NOT NULL,
  player_id INTEGER,
  plate_appearances BIGINT NOT NULL,
  at_bats BIGINT NOT NULL,
  hits BIGINT NOT NULL,
  total_bases BIGINT,
  home_runs BIGINT NOT NULL,
  walks BIGINT NOT NULL,
  hit_by_pitch BIGINT NOT NULL,
  sac_flies BIGINT NOT NULL,
  strikeouts BIGINT NOT NULL,
  batted_balls BIGINT NOT NULL,
  hard_hits BIGINT NOT NULL,
  barrels BIGINT NOT NULL,
  exit_velocity DOUBLE,
  pitches BIGINT,
  swings BIGINT,
  whiffs BIGINT,
  called_strikes BIGINT,
  fastball_velocity DOUBLE,
  out_of_zone_pitches BIGINT,
  chases BIGINT,
  zone_swings BIGINT,
  zone_contacts BIGINT
);

CREATE TABLE players (
  player_id INTEGER NOT NULL,
  full_name VARCHAR NOT NULL,
  first_name VARCHAR,
  last_name VARCHAR,
  boxscore_name VARCHAR,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  birth_date DATE,
  height VARCHAR,
  weight INTEGER,
  mlb_debut_date DATE,
  active BOOLEAN,
  sz_top DOUBLE,
  sz_bottom DOUBLE,
  source_game_pk INTEGER NOT NULL,
  source_date DATE NOT NULL,
  source_game_number INTEGER NOT NULL,
  PRIMARY KEY(player_id)
);

CREATE TABLE plays (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  at_bat_index INTEGER NOT NULL,
  inning INTEGER NOT NULL,
  half ENUM('top', 'bottom') NOT NULL,
  batter_id INTEGER NOT NULL,
  pitcher_id INTEGER NOT NULL,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  men_on_base VARCHAR,
  event VARCHAR,
  event_type VARCHAR,
  description VARCHAR,
  rbi INTEGER,
  is_out BOOLEAN,
  is_scoring_play BOOLEAN,
  final_balls INTEGER,
  final_strikes INTEGER,
  outs_after INTEGER,
  home_score_after INTEGER,
  away_score_after INTEGER,
  pitch_count INTEGER NOT NULL,
  launch_speed DOUBLE,
  launch_angle DOUBLE,
  total_distance DOUBLE,
  trajectory VARCHAR,
  hardness VARCHAR,
  hit_location VARCHAR,
  hit_coord_x DOUBLE,
  hit_coord_y DOUBLE,
  has_review BOOLEAN,
  review_type VARCHAR,
  review_overturned BOOLEAN,
  review_challenge_team_id INTEGER,
  review_player_id INTEGER,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(game_pk, at_bat_index)
);

CREATE TABLE probable_pitchers (
  game_pk INTEGER NOT NULL,
  side ENUM('home', 'away') NOT NULL,
  pitcher_id INTEGER,
  pitcher_name VARCHAR,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY(game_pk, side, observed_at)
);

CREATE TABLE raw_game_feeds (
  game_pk INTEGER NOT NULL,
  season INTEGER NOT NULL,
  feed_ts VARCHAR NOT NULL,
  fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
  json JSON NOT NULL,
  PRIMARY KEY(game_pk)
);

CREATE TABLE schema_migrations (
  file VARCHAR NOT NULL,
  applied_at TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY(file)
);

CREATE TABLE team_pitches (
  game_pk INTEGER,
  season INTEGER,
  at_bat_index INTEGER,
  pitch_index INTEGER,
  play_id VARCHAR,
  pitch_number INTEGER,
  inning INTEGER,
  half ENUM('top', 'bottom'),
  batter_id INTEGER,
  pitcher_id INTEGER,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  balls_before INTEGER,
  strikes_before INTEGER,
  outs_before INTEGER,
  pitch_type VARCHAR,
  pitch_type_desc VARCHAR,
  type_confidence DOUBLE,
  call_code VARCHAR,
  call_desc VARCHAR,
  description VARCHAR,
  is_in_play BOOLEAN,
  is_strike BOOLEAN,
  is_ball BOOLEAN,
  is_out BOOLEAN,
  start_speed DOUBLE,
  end_speed DOUBLE,
  spin_rate DOUBLE,
  spin_direction DOUBLE,
  extension DOUBLE,
  plate_time DOUBLE,
  plate_x DOUBLE,
  plate_z DOUBLE,
  pfx_x DOUBLE,
  pfx_z DOUBLE,
  x0 DOUBLE,
  y0 DOUBLE,
  z0 DOUBLE,
  vx0 DOUBLE,
  vy0 DOUBLE,
  vz0 DOUBLE,
  ax DOUBLE,
  ay DOUBLE,
  az DOUBLE,
  break_angle DOUBLE,
  break_length DOUBLE,
  break_y DOUBLE,
  break_vertical DOUBLE,
  induced_vertical_break DOUBLE,
  horizontal_break DOUBLE,
  zone INTEGER,
  sz_top DOUBLE,
  sz_bottom DOUBLE,
  launch_speed DOUBLE,
  launch_angle DOUBLE,
  total_distance DOUBLE,
  trajectory VARCHAR,
  hardness VARCHAR,
  hit_location VARCHAR,
  abs_challenged BOOLEAN,
  abs_overturned BOOLEAN,
  abs_challenge_team_id INTEGER,
  abs_challenger_id INTEGER,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  batting_team_id INTEGER,
  fielding_team_id INTEGER,
  official_date DATE,
  game_type VARCHAR,
  coded_state VARCHAR
);

CREATE TABLE team_plays (
  game_pk INTEGER,
  season INTEGER,
  at_bat_index INTEGER,
  inning INTEGER,
  half ENUM('top', 'bottom'),
  batter_id INTEGER,
  pitcher_id INTEGER,
  bat_side ENUM('L', 'R', 'S'),
  pitch_hand ENUM('L', 'R', 'S'),
  men_on_base VARCHAR,
  event VARCHAR,
  event_type VARCHAR,
  description VARCHAR,
  rbi INTEGER,
  is_out BOOLEAN,
  is_scoring_play BOOLEAN,
  final_balls INTEGER,
  final_strikes INTEGER,
  outs_after INTEGER,
  home_score_after INTEGER,
  away_score_after INTEGER,
  pitch_count INTEGER,
  launch_speed DOUBLE,
  launch_angle DOUBLE,
  total_distance DOUBLE,
  trajectory VARCHAR,
  hardness VARCHAR,
  hit_location VARCHAR,
  hit_coord_x DOUBLE,
  hit_coord_y DOUBLE,
  has_review BOOLEAN,
  review_type VARCHAR,
  review_overturned BOOLEAN,
  review_challenge_team_id INTEGER,
  review_player_id INTEGER,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  batting_team_id INTEGER,
  fielding_team_id INTEGER,
  official_date DATE,
  game_type VARCHAR,
  coded_state VARCHAR
);

CREATE TABLE team_season_batting (
  season INTEGER NOT NULL,
  team_id INTEGER,
  scope VARCHAR NOT NULL,
  split VARCHAR NOT NULL,
  teams BIGINT NOT NULL,
  games BIGINT NOT NULL,
  plate_appearances BIGINT NOT NULL,
  at_bats BIGINT NOT NULL,
  hits BIGINT NOT NULL,
  total_bases BIGINT,
  home_runs BIGINT NOT NULL,
  walks BIGINT NOT NULL,
  hit_by_pitch BIGINT NOT NULL,
  sac_flies BIGINT NOT NULL,
  strikeouts BIGINT NOT NULL,
  batted_balls BIGINT NOT NULL,
  hard_hits BIGINT NOT NULL,
  barrels BIGINT NOT NULL,
  exit_velocity DOUBLE
);

CREATE TABLE team_season_pitches (
  season INTEGER NOT NULL,
  team_id INTEGER,
  scope VARCHAR NOT NULL,
  pitches BIGINT NOT NULL,
  swings BIGINT NOT NULL,
  whiffs BIGINT NOT NULL,
  called_strikes BIGINT NOT NULL,
  fastball_velocity DOUBLE
);

CREATE TABLE team_season_pitching (
  season INTEGER NOT NULL,
  team_id INTEGER,
  scope VARCHAR NOT NULL,
  teams BIGINT NOT NULL,
  batters_faced BIGINT,
  outs BIGINT,
  runs BIGINT,
  earned_runs BIGINT,
  hits BIGINT,
  walks BIGINT,
  strikeouts BIGINT
);

CREATE TABLE team_season_swing_decisions (
  season INTEGER NOT NULL,
  team_id INTEGER,
  scope VARCHAR NOT NULL,
  out_of_zone_pitches BIGINT NOT NULL,
  chases BIGINT NOT NULL,
  zone_swings BIGINT NOT NULL,
  zone_contacts BIGINT NOT NULL
);

CREATE TABLE teams (
  team_id INTEGER NOT NULL,
  season INTEGER NOT NULL,
  name VARCHAR NOT NULL,
  team_name VARCHAR,
  abbreviation VARCHAR,
  location_name VARCHAR,
  short_name VARCHAR,
  team_code VARCHAR,
  league_id INTEGER,
  league_name VARCHAR,
  division_id INTEGER,
  division_name VARCHAR,
  venue_id INTEGER,
  venue_name VARCHAR,
  source_game_pk INTEGER NOT NULL,
  source_date DATE NOT NULL,
  source_game_number INTEGER NOT NULL,
  PRIMARY KEY(team_id, season)
);

CREATE VIEW pitch_outcomes AS SELECT *, (call_code IN ('S', 'W', 'M', 'T', 'F', 'L', 'X', 'D', 'E')) AS is_swing, (call_code IN ('S', 'W', 'M')) AS is_whiff, (call_code = 'C') AS is_called_strike, ("zone" BETWEEN 1 AND 9) AS is_in_zone, (pitch_type IN ('FF', 'SI')) AS is_fastball FROM team_pitches;

CREATE VIEW plate_appearances AS SELECT p.* REPLACE (CASE  WHEN (e.is_ball_in_play) THEN (p.launch_speed) ELSE NULL END AS launch_speed, CASE  WHEN (e.is_ball_in_play) THEN (p.hit_coord_x) ELSE NULL END AS hit_coord_x, CASE  WHEN (e.is_ball_in_play) THEN (p.hit_coord_y) ELSE NULL END AS hit_coord_y, CASE  WHEN (e.is_ball_in_play) THEN (p.launch_angle) ELSE NULL END AS launch_angle), e.is_at_bat, e.is_ball_in_play, e.is_walk, e.is_strikeout, e.bases FROM team_plays AS p INNER JOIN event_types AS e USING (event_type) WHERE e.is_plate_appearance;

CREATE VIEW team_pitches AS SELECT p.*, CASE  WHEN ((p.half = 'top')) THEN (g.away_team_id) ELSE g.home_team_id END AS batting_team_id, CASE  WHEN ((p.half = 'top')) THEN (g.home_team_id) ELSE g.away_team_id END AS fielding_team_id, g.official_date, g.game_type, g.coded_state FROM pitches AS p INNER JOIN games AS g USING (game_pk);

CREATE VIEW team_plays AS SELECT p.*, CASE  WHEN ((p.half = 'top')) THEN (g.away_team_id) ELSE g.home_team_id END AS batting_team_id, CASE  WHEN ((p.half = 'top')) THEN (g.home_team_id) ELSE g.away_team_id END AS fielding_team_id, g.official_date, g.game_type, g.coded_state FROM plays AS p INNER JOIN games AS g USING (game_pk);
